### ISSUE TITLE
Can't rerun npx gluestack-ui after manual clean

### ISSUE THREAD

**Issue by KannarFr** [gluestack/ui#242]
### Description

Due to https://github.com/gluestack/ui/issues/240, I manually removed files in `$HOME/.gluestack/cache/gluestack-ui/example/storybook/src/ui-components`, then I rerun `npx gluestack-ui` but looks like I shouldn't.

### CodeSandbox/Snack link

Not applicable

### Steps to reproduce

```bash
➜ npx gluestack-ui
 
gluestack/ui is not initialised in your project! 
✔ Do you wish to initialise it? (y/n)  … y
✔ Enter folder name where you want to add your components … components
| Pulling changes...  
Failed to pull the changes. 
GitError: error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.

    at Object.action (/home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:1274:25)
    at PluginStore.exec (/home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:1309:29)
    at /home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:1676:43
    at new Promise (<anonymous>)
    at GitExecutorChain.handleTaskData (/home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:1674:16)
    at GitExecutorChain.<anonymous> (/home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:1658:44)
    at Generator.next (<anonymous>)
    at fulfilled (/home/kannar/.npm/_npx/17e7bc1abc5c95a0/node_modules/simple-git/dist/cjs/index.js:55:24) {
  task: {
    commands: [ 'pull' ],
    format: 'utf-8',
    parser: [Function: parser],
    onError: [Function: onError]
  }
}
```

### Platform

- [ ] Android
- [ ] CRA
- [ ] Expo
- [ ] iOS
- [ ] Next

### Other Platform

React

**Comment by KannarFr** [comment]
Remove `$HOME/.gluestack` fixed the issue.

**Comment by AshwiniKumar007** [comment]
Hey @KannarFr ,
If this issue is solved, We can close this ticket.

**Comment by KannarFr** [comment]
The issue is not fixed, I did it manually and I think it should be handled by gluestack. Nope?

**Comment by AshwiniKumar007** [comment]
Surely @KannarFr. We will verify this from our end. 
Thanks for reporting.
